config/routes.rb
Temp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  get "/about_us" => "home#about"
  get "/help" => "help#index"

  resources :questions do  
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    resources :answers
    post :search, on: :collection
  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  root "questions#index" #this means the index of questions will be my homepage

end

app/models/question.rb
class Question < ActiveRecord::Base

	has_attached_file :image,
	:styles => { :medium => "300x300>", :thumb => "100x100>" },
	:default_url => ActionController::Base.helpers.asset_path("missing_:style.png")
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

 	# mount_uploader :image, ImageUploader

	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user

	has_many :answers, dependent: :destroy
	has_many :comments, through: :answers
	has_one :question_detail, dependent: :destroy
	belongs_to :user
	has_many :votes, dependent: :destroy
	has_many :voted_users, through: :votes, source: :user

	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations

	# validates_presence_of :title, presence: {message: "title can't be blank!!"}
	validates :title, presence: true, uniqueness: true
	#this validates if there are presence and it has to be unique
	validates_presence_of :description, message: "must be present"

	default_scope {order("created_at DESC")}

	scope :recent_ten, -> {order("created_at DESC").limit(10)}
	scope :recent_ten, lambda {order("created_at DESC").limit(10)}
	scope :created_after, lambda { |x| where(:created_at => (x)..(0.days.ago))}
	scope :recent, lambda {|x| order("created_at DESC").limit(x)}

	def self.recent_ten
		order("created_at DESC").limit(10)
	end


	
	# default_scope order("title ASC")


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_question, only: [:edit, :destroy, :update, :vote_up, :vote_down]
	# before_action :find_question, except: [:index, :new, :create]

	def index
		@recent_questions = Question.recent(3)
		@questions = Question.limit(10)
	end



	def create
		@question = Question.new(question_attributes)
		@question.user = current_user

		if @question.save
			expire_fragment "recent_questions"
			# flash[:notice] = "Your question was created successfully!"
			redirect_to questions_path, notice: "Your question was created!"
		else
			render :new
		end
	end


	def show
		@question = Question.find(params[:id])
		@answer = Answer.new
		if user_signed_in?
			@favorite = current_user.favorite_for(@question)
			# @vote = current_user.vote_for(@vote)
			@vote = user_signed_in? ? (current_user.vote_for(@question) || Vote.new) : Vote.new
		end
		@answers = @question.answers.ordered_by_creation
	end

	def new
		@question = Question.new

	end

	def edit
		# redirect_to root_path, alert: "Access Denied" unless can? :edit, @question
	end

	def update

		if @question.update_attributes(question_attributes)
			expire_fragment "recent_questions"
			redirect_to @question, notice: "Question updated successfully!"
		else
			flash.now[:error] = "Couldn't update!"
			render :edit
		end

		
	end

	def destroy

		if @question.destroy
			redirect_to questions_path, notice: "Question deleted!"
		else
			redirect_to questions_path, error: "We have trouble deleting it!"
		end

	end



	# def search
	# end



	private

	def question_attributes
		params.require(:question).permit([:title, :description, {category_ids: []}, :image])
	end

	def find_question
		@question = current_user.questions.find(params[:id])
		redirect_to root_path, alert: "Access Denied" unless @question
		# @question = current_user.questions.find_by_id(params[:id])
		#@question will be nil if there isn't a id like that
	end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
/ - if @question.errors.any?
/   %ul
/     - @question.errors.full_messages.each do |message|
/       %li= message
= simple_form_for @question, html: {class: "form-horizontal well" } do |f|
  = f.input :title, label: "Question Title"
  = f.input :description

  = f.input :image

  / = f.association :categories

  %br/
  = f.collection_check_boxes :category_ids, Category.order("title"), :id, :title,item_wrapper_class: "form-group"
  %br/
  = f.submit button_label, class: "btn btn-secondary"

app/views/questions/edit.html.haml
%h1 Editing Question
= render "form", button_label: "update it."

app/views/questions/index.html.haml
%h1 Recent Questions
- @recent_questions.each do |question|
  %h2= link_to question.title, question
  %p= question.description
  %p
    Created On: #{formatted_date(question.created_at)}
  %hr

%h1 Listing all questions!
= link_to "Create New Question", new_question_path
- @questions.each do |question|
  %h2= link_to question.title, question
  %p= question.description
  %p
    Created On: #{formatted_date(question.created_at)}
  %hr

app/views/questions/new.html.haml
%h1 Create New Question
= render "form", button_label: "Submit!"

app/views/questions/show.html.haml
%h1= @question.title
%p= @question.description
%p= formatted_date(@question.created_at)
%p

- if @question.image.present?
  = image_tag @question.image.url(:medium)

- if @favorite
  %p= button_to "Unfavorite", question_favorite_path(@question, @favorite), method: :delete, class: "btn btn-danger"
- else
  %p= button_to "Favorite", question_favorites_path(@question), method: :post, class: "btn btn-primary"
- if @question.favorited_users.present?
  Favorited Users:
  = @question.favorited_users.map(&:full_name).join(", ")


%br/
- if @question.categories.present?
  Categories (#{@question.categories.count}):
  = @question.categories.map(&:title).join(", ")


- if @vote.persisted? && @vote.is_up?
  = button_to "Undo", [@question, @vote], method: :delete, class: "btn btn-danger"
- else
  = form_for [@question, @vote] do |f|
    = f.hidden_field :is_up, value: true
    = f.submit "Vote Up", class: "btn btn-default"

%br/
- if @vote.persisted? && @vote.is_up?
  = form_for [@question, @vote] do |f|
    = f.hidden_field :is_up, value: false
    = f.submit "Vote Down", class: "btn btn-default"
- else
  = form_for [@question, @vote] do |f|
    = f.hidden_field :is_up, value: false
    = f.submit "Vote Down", class: "btn btn-default"

%br/



%br/
- if can? :edit, @question
  = link_to "Edit", edit_question_path(@question), class: "btn btn-default"
- if can? :destroy, @question
  = button_to "Delete", @question, method: :delete,                   
    data: {confirm: "Are you sure you want to delete this question?"},
    class: "btn btn-danger" 
%br/
= link_to "All Questions", questions_path




#answer-form= render "answers/form"


%hr
.answers= render @answers
/ - @answers.each do |answer|
/   = render "/answers/answer", answer: answer

%input.start{type: "button", value: "Click Me"}
%br
.success{style: "visibility: hidden"}
  %h1{style: "color: red"} SUCCESS!!!!!!!!!!!!!!

= label "enter_box-label", "Magical Box:"
= text_field_tag "enter_box", nil, class: "my_box"
%ul.enterbox

= label "box2-label", "Magical Box 2:"
= text_field_tag "box2", nil 
%span.box2-side

= form_tag "javascript:void(0);"
= text_field_tag "first_name", nil, :placeholder => "First Name"
= text_field_tag "last_name", nil, :placeholder => "Last Name"
= text_field_tag "email", nil, :placeholder => "Email"
= submit_tag "Save", class: "submit-box3"
.box3