config/routes.rb
Temp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  get "/about_us" => "home#about"
  get "/help" => "help#index"

  resources :questions do  
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    resources :answers
    post :search, on: :collection
  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  root "questions#index" #this means the index of questions will be my homepage

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :body, presence: :true

  before_save :capitalize_body

  scope :ordered_by_creation, -> { order("created_at DESC")}

  private

  def capitalize_body
    self.body.capitalize!
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :find_question

  def create
    @answer = @question.answers.new(answer_attributes)
  #   @answer.user = current_user

    respond_to do |format|
      if @answer.save
        # AnswerMailer.notify_question_owner(@answer).deliver
        AnswerMailer.delay.notify_question_owner(@answer)
        format.html { redirect_to @question, notice: "Answer Created Succefully!" }
        format.js { render }
      else
        format.html { render "/questions/show" }
        format.js { render :new }
      end
    end
  end

  def destroy
    respond_to do |format|
      @answer = @question.answers.find(params[:id])
      if @answer.user == current_user && @answer.destroy
        format.html { redirect_to @question, notice: "Answer Deleted!" }
        format.js { render }
      else
        format.html { redirect_to @question, alert: "we had trouble deleting the answer" }
        format.js { render js: "alert('ERROR');" }
      end
    end

  end



  private

  def answer_attributes
    params.require(:answer).permit([:body])
  end

  def find_question
    @question = Question.find params[:question_id]
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
.well{id: dom_id(answer)}
  .row
    %p= answer.body
    %p Created on #{formatted_date(answer.created_at)}
    .pull-right= button_to "Delete", question_answer_path(@question, answer), method: :delete, class: "btn btn-codecore", data: {confirm: "Are you sure you want to delete this?"}, remote: true
    = link_to "Remove", "javascript:void(0);", class: "btn btn-codecore remove-button"
    = link_to "Test Me", "javascript:void(0);", class: "btn btn-primary test-button"

app/views/answers/_form.html.haml
%h2 Add An Answer
- if @answer.errors.any?
  %ul
    - @answer.errors.full_messages.each do |message|
      %li= message

/ = form_for [@question, @answer] do |f|
= form_for @answer, url: question_answers_path(@question), remote: true do |f|
  = f.text_area :body, class: "form-control"
  %br
  = f.submit "Submit an answer", class: "btn btn-default"

app/views/answers/create.js.haml
$(".answers").prepend("#{j render 'answer', answer: @answer}");
$("##{dom_id(@answer)}").hide().fadeIn(1000);

- @answer = @question.answers.new
$("#answer-form").html("#{j render 'form'}")
$("#answer_body").val("");

app/views/answers/destroy.js.haml
$("##{dom_id(@answer)}").fadeOut(1000, function(){ $(this).remove(); });

app/views/answers/new.js.haml
$("#answer-form").html("#{j render 'form'}")